[kivy]
keyboard_mode = systemanddock

[graphics]
width = 1200
height = 800
minimum_width = 900
minimum_height = 600

[input]
# Disable problematic input providers
mouse = mouse
%(name)s = probesys,disable

[clipboard]
# Use sdl2 clipboard provider
sdl2 = True